### ISSUE TITLE
Mask in losses.py

### ISSUE THREAD

**Issue by BingCS** [lzx551402/tfmatch#2]
Hi Zixin,

I noticed that you apply a mask (line.134 of losses.py) with a threshold of 0.008. May I know the rules to select this value?

Best,
Bing

**Comment by zjhthu** [comment]
Hi Bing,

This threshold is used to filter too hard negative samples, which might harm the performance. This is also used in [hardnet](https://github.com/DagnyT/hardnet/blob/94e56839e1db5b90e303335ef26bce9daec71c3e/code/Losses.py#L101).

**Comment by BingCS** [comment]
Hi Jiahui,

Many thanks for your kind reply. To safely remove such samples, "dist_mat_without_min_on_diag" (line 136) should plus "mask*10" as HardNet does instead of "mask". Have I got that right?

Best,
Bing

**Comment by zjhthu** [comment]
For normalized features, the maximum of dist mat is 1.0, so it is ok to plus "mask". "+mask*10" is indeed a more safe way.

**Comment by BingCS** [comment]
Hi Jiahui,

If ‖𝑥‖=‖𝑦‖=1, the triangle inequality gives ‖𝑥−𝑦‖≤‖𝑥‖+‖𝑦‖=2. Thus, the values in dist_mat should range from 0.0 to 2.0. It might not be safe to just plus "mask".

Best,
Bing

**Comment by zjhthu** [comment]
Sorry, you are right. But I think this might only have a slight impact. I will fix it.

**Comment by zjhthu** [comment]
thanks for the issue, fixed.
